# Site settings
title: Fernando Soares
description: >
  UI/UX Design & Front End em Florian√≥polis.
cover: http://www.updateordie.com/wp-content/uploads/2017/03/gor-758x383.jpg

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frrrnd.design" # the base hostname & protocol for your site
permalink: /:title/

future: true
lang: pt_BR

author:
  fullname: Fernando Soares
  github: frrrnd
  twitter: frrrnd
  dribbble: fernando
  instagram: ferspeak
  medium: frrrnd
  codepen: frrrnd
  linkedin:
  googleplus: https://plus.google.com/u/0/+FernandoSoares0
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown